name: Build and Deploy Python Application

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

# If you have envirement variables, you should add them here

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build . -t ghcr.io/${REPO_NAME}:latest
          docker push ghcr.io/${REPO_NAME}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to server
        run: |
          # Add your deployment steps here
          echo "Deploying to server"

    #   - name: Deploy
    #     run: railway up --service {id}
    #     env:
    #       RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
